#!/bin/bash

#operadores booleanos: AND : && -- OR : ||
if [ $USER = jussara ] && [ -w $HOME/.bashrc ]
then
	echo "O usuario $USER tem permissão para alterar o arquivo"
else
	echo "O usuário $USER não pode alterar o arquivo agora"
fi


