#!/bin/bash

#Radiolist

cidade=$(whiptail --title "Listagem de Cidades" --radiolist \
"Qual cidade deseja visitar?" 15 50 5 \
"Londres" "Inglaterra" ON \
"Berlim" "Alemanha" OFF \
"Toronto" "Canadá" OFF \
"Abu Dhabi" "Emirados Árabes" OFF \
"Pequim" "China" OFF 3>&1 1>&2 2>&3)

status=$?
if [ $status = 0 ]
then
	echo "A cidade escolhida foi: "$cidade
else
	echo "Você não escolheu nenhuma cidade."
fi

#Checklist
cidade=$(whiptail --title "Listagem de Cidades" --checklist --fb \
"Qual cidade deseja visitar?" 15 50 5 \
"Londres" "Inglaterra" ON \
"Berlim" "Alemanha" OFF \
"Toronto" "Canadá" OFF \
"Abu Dhabi" "Emirados Árabes" OFF \
"Pequim" "China" OFF 3>&1 1>&2 2>&3)

status=$?
if [ $status = 0 ]
then
	echo "A cidades escolhidas foram: "$cidade
else
	echo "Você não escolheu nenhuma cidade."
fi


